// P1 deprecated root stub
// DO NOT EDIT THIS FILE. Canonical source: src/presentation/shell/app.js
(function () {
  var payload = { file: 'app.js', canonical: 'src/presentation/shell/app.js', phase: 'P1' };
  var line = '[P1][INVARIANT] legacy-root-file-loaded ' + JSON.stringify(payload);
  try { if (typeof console !== 'undefined' && console.error) console.error(line); } catch (_) {}
  throw new Error('Deprecated root file loaded: app.js. Use src/presentation/shell/app.js instead.');
})();
