// P1 deprecated root stub
// DO NOT EDIT THIS FILE. Canonical source: src/presentation/lighting/lighting-editor.js
(function () {
  var payload = { file: 'lighting-editor.js', canonical: 'src/presentation/lighting/lighting-editor.js', phase: 'P1' };
  var line = '[P1][INVARIANT] legacy-root-file-loaded ' + JSON.stringify(payload);
  try { if (typeof console !== 'undefined' && console.error) console.error(line); } catch (_) {}
  throw new Error('Deprecated root file loaded: lighting-editor.js. Use src/presentation/lighting/lighting-editor.js instead.');
})();
