// P1 deprecated root stub
// DO NOT EDIT THIS FILE. Canonical source: src/infrastructure/legacy/state.js
(function () {
  var payload = { file: 'state.js', canonical: 'src/infrastructure/legacy/state.js', phase: 'P1' };
  var line = '[P1][INVARIANT] legacy-root-file-loaded ' + JSON.stringify(payload);
  try { if (typeof console !== 'undefined' && console.error) console.error(line); } catch (_) {}
  throw new Error('Deprecated root file loaded: state.js. Use src/infrastructure/legacy/state.js instead.');
})();
